### ISSUE TITLE
Update the readme (filetype?)

### ISSUE THREAD

**Issue by gilacost** [the-mikedavis/tree-sitter-iex#9]
- I am using neovim and [`nvim-treesitter`](https://github.com/nvim-treesitter/nvim-treesitter)
- I followed the advanced setup for installing a [non-maintained parser](https://github.com/nvim-treesitter/nvim-treesitter)

### Appears installed:

![Screenshot 2022-01-14 at 08 30 23](https://user-images.githubusercontent.com/6720169/149476866-a2df0df2-6360-4e45-b1d4-3a4b0b8c1752.png)

### Treesitter lua conf:

```lua
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.iex = {
  install_info = {
    url = "~/projects/tree-sitter-iex", -- local path or git repo
    -- url = "git@github.com:elixir-lang/tree-sitter-iex.git", -- local path or git repo
    files = {"src/parser.c"}
  },
--  filetype = "zu", -- if filetype does not agrees with parser name
--  used_by = {"bar", "baz"} -- additional filetypes that use this parser
}
```
I think the problem has to do with the filetype, once we sort this I would be happy to add some extra docs into the readme about how to install/use this.

**Comment by the-mikedavis** [comment]
:wave: hello!

I tried out integrating the grammar with nvim with those instructions and I think there are some pitfalls you may want to check.

The first from that [adding parsers](https://github.com/nvim-treesitter/nvim-treesitter#adding-parsers) section:

>  Note that neither `:TSInstall` nor `:TSInstallFromGrammar` copy query files from the grammar repository. If you want your installed grammar to be useful, you must manually add query files to your local nvim-treesitter installation.

So I copied `queries/highlights.scm` from this repository into `~/.local/share/nvim/plugged/nvim-treesitter/queries/iex/`

The next issue I ran into is that nvim-treesitter does injections very differently from tree-sitter-cli, so the `injections.scm` in this repository won't work. Instead I tried some like

```tsq
(evaluation_block (prompt_line (expression) @elixir))
(result) @elixir
```

which works reasonably well, but has some limitations: nvim-treesitter does not currently implement "combined" injections, so multi-line expressions like

```iex
iex> if true do
...>   :ok
...> end
:ok
```

will show the `end` as unhighlighted. Based on [a recent PR](https://github.com/nvim-treesitter/nvim-treesitter/pull/2232#issuecomment-1009371077), it looks like one of the primary nvim-treesitter maintainers is interested in solving that problem soon.

The last issue is filetype as you mention. You'll need some vimscript so nvim knows that `*.iex` files should use tree-sitter-iex. [Here's](https://github.com/nvim-treesitter/nvim-treesitter/blob/a76e1eb89d57e25cedbc71d6bf8e2d2c23d5d85b/ftdetect/elixir.vim) how it works for elixir, but according to [these docs](https://github.com/nvim-treesitter/nvim-treesitter/tree/a76e1eb89d57e25cedbc71d6bf8e2d2c23d5d85b#feature-x-does-not-work-for-language) (the third paragraph), you can try `:set filetype=iex` and that should get the highlights working. Since iex isn't really a file-type, though, I'm not sure it makes sense to setup a rule to mark `*.iex` as iex. This gammar is mostly meant for injections like in markdown blocks.

**Comment by the-mikedavis** [comment]
> I would be happy to add some extra docs into the readme about how to install/use this.

In general I would prefer to keep installation/usage instructions for specific editors out of the readme since the grammar can be used by multiple editors. IMO troubleshooting/installation should be in the editor/plugin's docs since it varies so much between editors (as in this issue, :point_up: all of those pitfalls are nvim-treesitter specific).

Ideally it'd be great to have this grammar added to nvim-treesitter. I don't use nvim regularly so I probably shouldn't be the maintainer though. Would you be interested in opening a PR in nvim-treesitter to integrate this grammar?

**Comment by gilacost** [comment]
Wow, thanks for your messages that was quick!  I really appreciate your answers 💯 . 
Regarding your second comment, yeah it makes sense, specifics should not be added in this repo's readme. 

I am happy to help, I will come back to you 😉 .

**Comment by gilacost** [comment]
I am going to park this for the time being, I use nix to configure my environment and I am struggling to test locally. So far, if someone is interested:
* I installed neovim and it's plugins with [home-manager](https://github.com/nix-community/home-manager/blob/0b197562ab7bf114dd5f6716f41d4b5be6ccd357/modules/programs/neovim.nix). Fins here my [dot-files](https://github.com/gilacost/dot-files/blob/cde7566713ecb74e8cbf54ec50a20cf2e131775c/home.nix#L341).
* Then I tried to find the derivation where tree-sitter modules are installed.
```bash 
nix-store --query --requisites /run/current-system
```
Home-manager installs nvim treesitter plugin in a derivation that looks like this:
```bash
/nix/store/kw4m0krl18kh2wfdhjnkazd3kd8dqnvg-vim-pack-dir/pack/home-manager/start/vimplugin-nvim-treesitter/
```
Iex appears as installed:

<img width="336" alt="Screenshot 2022-01-14 at 19 53 09" src="https://user-images.githubusercontent.com/6720169/149576731-c3408171-5c15-4a25-acf7-384468797215.png">

But when I set the filetype it does not parse as I would expect 😄.

![](http://g.recordit.co/BRkHC29G2K.gif)
